name: 'Deploy Production'

on:
  push:
    tags:
      - v**

jobs:
  DeployProduction:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Docker Image Url
        id: image
        env:
          URL: harbor.ncuos.com/genius-auth/gate
        run: |
          echo LATEST=${URL}:latest >> $GITHUB_OUTPUT
          echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Build Site
        run: |
          cd web
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Build Binary
        env:
          GOPRIVATE: github.com/ncuhome
          CGO_ENABLED: 0
        run: go build -gcflags=-trimpath=$GOPATH -asmflags=-trimpath=$GOPATH -ldflags '-extldflags "-static" -s -w' -o runner -tags="nomsgpack" ./cmd/gate

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag ${{ steps.image.outputs.VERSION }} \
          --tag ${{ steps.image.outputs.LATEST }}

      - name: Push
        run: |
          docker push ${{ steps.image.outputs.VERSION }}
          docker push ${{ steps.image.outputs.LATEST }}